### ISSUE TITLE
for journal entry - generator 

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#10]
[https://gist.github.com/maggienj/39d3b30afec9de22c0a3ee476ac21b31](https://gist.github.com/maggienj/39d3b30afec9de22c0a3ee476ac21b31)

**Comment by klahnakoski** [comment]
These are good notes!  The Outreachy project recommends you write a
blog, maybe this would be good content.  I suggest you write your notes
in markdown so they format a bit nicer.  Then you can host them on
Github, or even keep a collection in a repo.

I use http://markdownpad.com/ , but it does not format tables and some
other things that Github's flavour of markdown can do. If you find a
good markdown editor, please tell me about it.

**Comment by maggienj** [comment]
Sure, will put this in a blog.
[http://elasticsearchpy.blogspot.com/2017/05/for-journal-entry-generator.html](http://elasticsearchpy.blogspot.com/2017/05/for-journal-entry-generator.html)

Will check markdownpad and others.
