### ISSUE TITLE
[size] must be greater than 0

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#17]
several unit tests raise this err...
[size] must be greater than 0

**Comment by maggienj** [comment]
It appears that size = 1 would work in ES5 
as per, https://github.com/elastic/kibana/issues/8330

ref: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_aggregations_changes.html

**Comment by maggienj** [comment]
several unit tests use this size=0, one sample unit-test is TestEdge1.test_count_rows

**Comment by klahnakoski** [comment]
Close this.  You can deal with this issue in the context of fixing a particular test case.
