### ISSUE TITLE
For Journal Entry - unitTest - test_count_rows :  size=0 in outer query

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#19]
**Unit Test:** test_count_rows

Try to keep size as 0 in that outer query level 

Try to remove size param if size = 0. (conditional check)
And then run unit_test, test_count_rows .

**Comment by klahnakoski** [comment]
Maybe close this?  There are four `test_count_rows` tests, and I do not know which you are referring to here.

**Comment by maggienj** [comment]
It is probably the same one, which is TestEdge1.
 I'll prefix/rename to "For Journal Entry..." as issue#24 refers to the same TestEdge1.test_count_rows.
