### ISSUE TITLE
For journal entry: Key values - in dict

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#21]
For journal entry:

```
mydict = {'george':16,'amber':19}
print mydict.keys()[mydict.values().index(16)] # Prints george
```

Or in Python 3.x:

```
mydict = {'george':16,'amber':19}
print(list(mydict.keys())[list(mydict.values()).index(16)]) # Prints george
```

Basically, it separates the dictionary's values in a list, finds the position of the value you have, and gets the key at that position.

More about keys() and .values() in Python 3: Python: simplest way to get list of values from dict?

This could be used only if you are passing the value and fetching the key name.

Because, this doesn't loop through in the "for loop" and fetches the keyname for that index value.

Marking it here to remember as this is something interesting to look at... as it appears to be "missing the looping in a for loop" and gets to the index value straight. 
Not sure , how the internal works in python for this to not to loop and get straight to the index.
For now, wanted to mark this here, so that I can lookup later on to remember these specialties in Python.

Ref: As I was googling for something last week, this article popped up, so storing it here for future reference.
https://stackoverflow.com/questions/8023306/get-key-by-value-in-dictionary

**Comment by klahnakoski** [comment]
Rather than finding values that match, then getting the matching keys, do it with a list comprehnesion using `items()`:

    mydict = {'george':16,'amber':19}
    print([k for k,v in mydict.items() if v==16]) # Prints ["george"] in an array, in case of multiple matches

**Comment by maggienj** [comment]
I see, that is very comprehensive. 

Hope the `**below** `multi-line code doesn't affect the effectiveness of **internal processing of python for this block**, though they both produce the same results.  Is this assumption correct?

```
>>> mydict = {'george':16,'amber':19}
>>> for k,v in mydict.items():
	if v== 16:
		print([k])

['george']
>>> 
```

**Comment by klahnakoski** [comment]
that is not the same, this is

    mydict = {'george':16,'amber':19}
    matches = []
    for k,v in mydict.items():
        if v==16:
            matches.append(k)
    print(matches) # Prints ["george"] in an array, in case of multiple matches

" maybe it will help to think of a list comprehension as in the same order as a SQL query: SELECT f(x) FROM y WHERE z -> [f(x) for x in y if z "

**Comment by klahnakoski** [comment]
I think we are done with this issue.  Please close.
