### ISSUE TITLE
TestAggOps - ignored tests

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#26]
Tried to see which test to pick next, so ran TestAggOps , as "test_max_object_value" is part of this aggOps category.

Four were ignored.
and the rest passed in TestAggOps .

Test_many_aggs_on_value - Skipped: require dynamic typing before primitives are expected to pass
Test_max_on_tuple - Skipped: requires scripted metric aggregations
Test_median_on_value - Skipped: not expected to pass yet
Test_simpletest_on_value - Skipped: require dynamic typing before primitives are expected to pass 

May be will choose another category to choose a different test.

**Comment by klahnakoski** [comment]
We will get to these ignored tests when we decide to work on the typed JSON (tjson) feature.  Close this issue
