### ISSUE TITLE
Fix TestSetOps.test_max_limit

### ISSUE THREAD

**Issue by klahnakoski** [maggienj/ActiveData#27]
Looks like the limit is too large: Rather than reducing the max limit, change the es5 config file to accept 50K documents returned

**Comment by maggienj** [comment]
branch issue27 created. 
Changes made, committed and pushed.

**Comment by maggienj** [comment]
made some changes...  c656df762817b34b896f3e6fba81deb98c3293de   and getting this err.
Somewhere, size is set to 10,000 
```
caused by
	ERROR: Internal Server Error: {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [50000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"testing_000_u20170613_152313","node":"OX5gNnXQRtW6gThYBtxJ4w","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [50000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}],"caused_by":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [50000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}},"status":500}
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\env\elasticsearch.py", line 760, in post
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\env\elasticsearch.py", line 1100, in search
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\es09\util.py", line 40, in post
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\es14\setop.py", line 193, in extract_rows
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\es14\setop.py", line 63, in es_setop
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx_usingES.py", line 159, in query
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx.py", line 71, in run
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\actions\jx.py", line 62, in jx_query
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\__init__.py", line 54, in output
	
```

**Comment by klahnakoski** [comment]
As per the error

    This limit can be set by changing the [index.max_result_window] index level setting.

Update your elasticsearch config file, and restart es.  Once you have confirmed the config change works, then change the elasticsearch.yml file in tests directory to the same.

**Comment by klahnakoski** [comment]
I noticed you changed a config file, but not one that is in the tests directory.  Did you change the config file that your ES is using (in the `config` subdirectory of your elasticsearch installation).

**Comment by maggienj** [comment]
Just... soon after the commit, i did change in the tests/config file too and that raised the same err too...  since no reaction to this change, reverted this.
But, I didn't restart  ES. 

I will now, try to restart ES and then see if that resolves this err...

**Comment by maggienj** [comment]
added max_result_window param to tests/config/elasticsearch.yml  e2a84c11e855066ae664f41cba6da79520fecab5
restarted ES. 
still the same err.  
will restart ES once again and probably check if any other param needs to be fixed for that 10,000.

**Comment by klahnakoski** [comment]
as per https://github.com/maggienj/ActiveData/issues/40 the error coming from ES says that this parameter is not supposed to be in a *.yml file.

**Comment by maggienj** [comment]
fixed.
