### ISSUE TITLE
Make pull request for es5

### ISSUE THREAD

**Issue by klahnakoski** [maggienj/ActiveData#28]
It is clearer that I make this an issue:

* Use github to make a pull request to from you es5 branch to my es5 branch
* Make pull requests for each issue branch you have completed to my es5 branch

Then I can review all the changes you made to a branch in a single package (a pull request).

**Comment by maggienj** [comment]
I just created a pull request from issue:22 to upstream es5 branch. Please ignore that pull request. 
I will create a new pull request from the downstream es5 branch.

**Comment by maggienj** [comment]
New pull request created from downstream es5 to upstream es5.

**Comment by klahnakoski** [comment]
you now know the process.
