### ISSUE TITLE
For Journal Entry - Imp Points - Summary - This thread will be an open thread for jotting down imp points.

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#38]
1) Use Log.note for console logging.

2) Use es5 branch as the base for future "issue# branch creations"

3) tjson stands for typed_json and it cannot be True till a certain point(??). So, while executing tests, tjson param value should be False.

4) When an issue# is fixed, then ensure it's a true fix by peer review, before merging it to maggienj/es5 branch.

5) Merge with -ff switch or check the box for "Fast Forward" if using the merge feature in PyCharm / TortoiseGit. 

5) Once in a while pull upstream data from klahnakoski:es5 to maggienj:es5.
( As of the moment, this is not in synch...   pull upstream was already done and it appears to not to have pulled. )

**Comment by klahnakoski** [comment]
On #5:

* merge from issue branches into main branch using `--no-ff` - you should not need to do this often; the merge is done on the main repo, and pulling from upstream will give you this merge.
* sometimes you want to merge the main branch into your issue branch (so you can use the features of the main branch): when doing this, use default merge (with ff).

**Comment by klahnakoski** [comment]
On #6 

Pull `git pull upstream es5` everyday, and every time you make a new issue branch.
