### ISSUE TITLE
For Journal Entry - git pull upstream steps

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#39]
Steps to pull upstream es5 to origin/es5 :
```
1- C:\Users\user\PycharmProjects\ActiveData>git checkout es5
2- C:\Users\user\PycharmProjects\ActiveData>git status
3- C:\Users\user\PycharmProjects\ActiveData>git pull origin
4- C:\Users\user\PycharmProjects\ActiveData>git pull upstream es5  
```
**step-4** does the pull and merge....  just one command is sufficient. So that, a separate "merge" step is not required. 
In the future, just use "git pull upstream es5" .
This works, because, the branch name is part of it. 
If the branch name is not part of it, then it puts it in upstream/es5 and that's why we have to use the merge command separately to merge the content from "upstream/es5" into "origin/es5".
This description is just to remember that it is a **two step process** vs **one step process** when "upstream with the branch name is specified in command params"

What follows is just a sample of what we were trying to do today, to show the two step process and the one step process, though both works fine.

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\user>cd py*

C:\Users\user\PycharmProjects>cd Active*

C:\Users\user\PycharmProjects\ActiveData>git status
On branch es5
Your branch is up-to-date with 'origin/es5'.
nothing to commit, working directory clean

C:\Users\user\PycharmProjects\ActiveData>git pull origin
Already up-to-date.

C:\Users\user\PycharmProjects\ActiveData>git pull upstream
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 18 (delta 12), reused 18 (delta 12), pack-reused 0
Unpacking objects: 100% (18/18), done.
From https://github.com/klahnakoski/ActiveData
   b7ce860..106d2bf  dev        -> upstream/dev
   ddbedca..73c6acf  es5        -> upstream/es5
You asked to pull from the remote 'upstream', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.

C:\Users\user\PycharmProjects\ActiveData>git status
On branch es5
Your branch is up-to-date with 'origin/es5'.
nothing to commit, working directory clean

C:\Users\user\PycharmProjects\ActiveData>git checkout es5
Already on 'es5'
Your branch is up-to-date with 'origin/es5'.

C:\Users\user\PycharmProjects\ActiveData>git merge upstream/es5
Removing resources/scripts/setup_frontend_r3_large.sh
Merge made by the 'recursive' strategy.
 docs/jx_expressions.md                       |   8 +-
 pyLibrary/queries/expressions.py             | 133 ++++++++++++++++----------
 resources/scripts/setup_frontend_r3_large.sh | 137 ---------------------------
 tests/test_jx/test_agg_ops.py                |   3 +-
 tests/test_jx/test_expressions_w_set_ops.py  |  33 +++++++
 5 files changed, 120 insertions(+), 194 deletions(-)
 delete mode 100644 resources/scripts/setup_frontend_r3_large.sh

C:\Users\user\PycharmProjects\ActiveData>git checkout es5
Already on 'es5'
Your branch is ahead of 'origin/es5' by 11 commits.
  (use "git push" to publish your local commits)

C:\Users\user\PycharmProjects\ActiveData>git pull upstream es5
From https://github.com/klahnakoski/ActiveData
 * branch            es5        -> FETCH_HEAD
Already up-to-date.

C:\Users\user\PycharmProjects\ActiveData>git checkout issue27
Switched to branch 'issue27'
Your branch is up-to-date with 'origin/issue27'.

C:\Users\user\PycharmProjects\ActiveData>

**Comment by klahnakoski** [comment]
I suggest that all these `For Journal` entries belong to your personal notes, not as issues.  They are missing a lot of context that is required to understand them; they should not be in the open. Many of us have a notebook (with real paper) that stores these facts.
