### ISSUE TITLE
issue27a - dup issue / branch to check it properly with ":"

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#40]
Created issue27a branch , it contains no changes pertinent to index.max_result_window, as it was branched out of es5, the base branch which doesn't contain any changes related to this issue, as of now.

Tried to make a change just to c:\elasticsearch522\config\elasticsearch.yml

Added this line with a proper ":"
index.max_result_window: 1  (just tried with 1 )

Result:  To make this change effective, tried to stop and start ES server. 
ES server didn't start. It closed itself immediately because of this change in config file.
Checked ES log and what is shown below is the log content...

```
Found index level settings on node level configuration.

Since elasticsearch 5.x index level settings can NOT be set on the nodes
configuration like the elasticsearch.yaml, in system properties or command line
arguments.In order to upgrade all indices the settings must be updated via the
/${index}/_settings API. Unless all settings are dynamic all indices must be closed
in order to apply the upgradeIndices created in the future should use index templates
to set default values.

Please ensure all required values are updated on all indices by executing:

curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.max_result_window" : "1"
}'


```

**Comment by maggienj** [comment]
not sure, where / how this line translates to in activedata's python to es settings...

```
curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.max_result_window" : "1"
}'
```

**Comment by maggienj** [comment]
not sure, where this "preserve_existing" setting can be set... 
Should this be also set in basic_schema.json.template ?

though, we tried in basic_schema.json.template for setting, index.max_result_window.....  where/how is this translated from python to es?

**Comment by klahnakoski** [comment]
you did not need to make a new issue27:  Instead, git checkout issue27, make your fixes, then commit and push your changes.  The pull request will update.

On the subject of

    curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
      "index.max_result_window" : "1"
    }'

This has the same effect as updating your `elasticsearch.yml` file (not the same as updating the *.json.template file).  The `preserve_existing=true` will ensure elasticsearch does not remember your change after a reboot.

**Comment by klahnakoski** [comment]
close this issue, and continue the discussion in the pull request (or the original issue)
