### ISSUE TITLE
curious to know why we convert 'dict' to 'data' type

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#62]
curious to know why we convert 'dict' to 'data' type
i'm sure there is a reason behind it, which i dont get it.

```
def wrap(v):
    type_ = _get(v, "__class__")

    if type_ is dict:
        m = object.__new__(Data)
        _set(m, "_dict", v)
        return m


```

**Comment by klahnakoski** [comment]
`dict` is difficult to use;
* it is prone to `KeyError`s
* it is inelegant for property access
* it requires lots of lines to construct complex data structures

https://github.com/klahnakoski/mo-dots
